### ISSUE TITLE
MT compatible analyzer

### ISSUE THREAD

**Issue by himanshudce** [cdli-gh/sumor#1]
Hi, to integrate with the MT(Machine Translation) system I am looking for an API/function call where I can pass a sentence and get the morph analysis of that sentence.
Example -
sentence. - “sza3-bi su-ga nig2-ka9 sze-ka”
output - ^sza3_bi<n><abl><3-sg-nh-poss>$ ^su_ga<vblex><pt><nf>$ ^nig2_ka9<n>$ ^sze_ka<n><gen>$
(*output in any format will work, can be converted from my end)

**Comment by chiarcos** [comment]
The morphological analyzer operates over words, not sentences, but see [analyse.py](https://github.com/cdli-gh/sumor/blob/main/analyze.py#L70) on how to use `sfst.analyse(form)`. 
In principle, that does what you want, but it does not disambiguate and it's not sufficiently operational. In particular, conversion from signs to morphemes doesn't work yet (see #3).
